spring:
  application:
  name: libraryfull

  datasource:
    url: jdbc:h2:mem:libraryfull
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console